# Generated by Django 4.2.6 on 2023-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accessrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
