# Generated by Django 4.2.6 on 2023-12-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_webpage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='date',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(default='http://url.com'),
        ),
    ]
